CREATE DATABASE NEW_PROJECT;
USE NEW_PROJECT;
SELECT * FROM SWIGGY;
SELECT COUNT(*) FROM SWIGGY;  #8680
DESCRIBE SWIGGY;

#------Duplicate checking------
CREATE TEMPORARY TABLE S_NEW 
SELECT DISTINCT * FROM SWIGGY;  #Creating a new temporary table "S_NEW" with distinct rows from "SWIGGY"
TRUNCATE SWIGGY;  #Deleting all rows from "SWIGGY"
INSERT INTO SWIGGY
SELECT * FROM S_NEW; #Adding all distinct values from "S_NEW" into "SWIGGY"
SELECT COUNT(*) FROM SWIGGY;  #8680,hence no duplicates

#------Column heading renaming------
ALTER TABLE SWIGGY
    RENAME COLUMN `Delivery time` TO `Delivery_Time`,
    RENAME COLUMN `Avg ratings` TO `Average_Ratings`,
    RENAME COLUMN `Total ratings` TO `Total_Ratings`,
    RENAME COLUMN `Food type` TO `Food_Type`;
    
#------Null value checking------
SELECT * FROM SWIGGY WHERE ID IS NULL OR AREA IS NULL OR CITY IS NULL OR RESTAURANT IS NULL 
OR PRICE IS NULL OR AVERAGE_RATINGS IS NULL OR TOTAL_RATINGS IS NULL OR FOOD_TYPE IS NULL 
OR ADDRESS IS NULL OR DELIVERY_TIME IS NULL;                                                      #No null values found

#------Data trimming------
UPDATE SWIGGY SET CITY = TRIM(CITY);
UPDATE SWIGGY SET RESTAURANT = TRIM(RESTAURANT);
SET SQL_SAFE_UPDATES=0;

#------Adding a new column------
ALTER TABLE SWIGGY ADD COLUMN RATING_CATEGORY varchar(50);
UPDATE SWIGGY SET RATING_CATEGORY = CASE 
    WHEN Average_Ratings < 2 THEN 'Poor'
    WHEN Average_Ratings BETWEEN 2 AND 3.5 THEN 'Average'
    WHEN Average_Ratings BETWEEN 3.5 AND 4.5 THEN 'Good'
    ELSE 'Excellent' END;

#------Univariant analysis------
#Count of Restaurants
SELECT COUNT(*) AS TOTAL_RESTAURANT FROM SWIGGY;  #8680
SELECT count(distinct RESTAURANT) FROM SWIGGY;  #7865
#Number of Restaurants in Different Cities
SELECT CITY,COUNT(*) AS NO_OF_RESTAURANTS FROM SWIGGY GROUP BY CITY ORDER BY NO_OF_RESTAURANTS DESC;
#Count of Restaurant in each Area
SELECT AREA,COUNT(*) AS RESTAURANTS FROM SWIGGY GROUP BY AREA ORDER BY RESTAURANTS DESC LIMIT 10;
#Count of Restaurant Branches across cities
SELECT RESTAURANT,COUNT(*) AS NO_OF_BRANCHES FROM SWIGGY GROUP BY RESTAURANT ORDER BY NO_OF_BRANCHES DESC LIMIT 10;

#Unique addresses
SELECT COUNT(DISTINCT Address) AS Unique_Addresses FROM SWIGGY;

#Top 5 most frequent addresses
SELECT Address, COUNT(*) AS Frequency FROM SWIGGY GROUP BY Address ORDER BY Frequency DESC 
LIMIT 5;


#Count of distinct city
SELECT DISTINCT CITY FROM SWIGGY;  
SELECT count(distinct CITY) FROM SWIGGY;  #9

#Average ratings,Min and Max ratings
SELECT AVG(AVERAGE_RATINGS) AS AVG_RATING FROM SWIGGY;  #3.655103686636279
SELECT MIN(AVERAGE_RATINGS) AS MIN_RATING FROM SWIGGY;  #2
SELECT MAX(AVERAGE_RATINGS) AS MAX_RATING FROM SWIGGY;  #5

#Count the number of restaurants for each type of food.
SELECT FOOD_TYPE,count(*) AS RESTAURANT_COUNT FROM SWIGGY GROUP BY FOOD_TYPE ORDER BY RESTAURANT_COUNT DESC;

#Price distribution
SELECT AVG(PRICE) AS AVG_PRICE FROM SWIGGY;  #348.4444700460829
SELECT MIN(PRICE) AS MIN_PRICE FROM SWIGGY;  #0
SELECT MAX(PRICE) AS MAX_PRICE FROM SWIGGY;  #2500

#Delivery time
SELECT AVG(DELIVERY_TIME) AS AVG_DT FROM SWIGGY;  #53.9671
SELECT MIN(DELIVERY_TIME) AS MIN_DT FROM SWIGGY;  #20
SELECT MAX(DELIVERY_TIME) AS MAX_DT FROM SWIGGY;  #109

#Restaurant with "excellent rating"
SELECT COUNT(RESTAURANT) AS TOP_RATING FROM SWIGGY WHERE RATING_CATEGORY="excellent";  #324

#Delivery Time Count
SELECT CASE WHEN Delivery_Time < 30 THEN 'Under 30 Minutes'
        WHEN Delivery_Time BETWEEN 30 AND 60 THEN '30-60 Minutes'
        ELSE 'Over 60 Minutes' END AS Delivery_Time_Range,
    COUNT(*) AS Restaurant_Count
FROM SWIGGY GROUP BY Delivery_Time_Range;
#30-60 Minutes	  5843
#Over 60 Minutes   2683
#Under 30 Minutes  154

SELECT * FROM SWIGGY WHERE PRICE=0;  #There are 5 rows whose PRICE column is 0

#------Bivariant analysis------
#Average Rating by Food Type
SELECT FOOD_TYPE,AVG(AVERAGE_RATINGS) AS AVG_RATING FROM SWIGGY GROUP BY FOOD_TYPE ORDER BY AVG_RATING DESC;  #Healthy Food,Salads,Desserts,Beverages	5

#Average Price by Food Type
SELECT FOOD_TYPE,AVG(PRICE) AS AVG_PRICE FROM SWIGGY GROUP BY FOOD_TYPE ORDER BY AVG_PRICE DESC;  #Japanese,Korean,Barbecue	2500

#Total ratings by city
SELECT CITY,SUM(TOTAL_RATINGS) AS TOTAL_SUM FROM SWIGGY GROUP BY CITY ORDER BY TOTAL_SUM DESC;  #Hyderabad	330270  MAY BE BECAUSE OF MORE POPULATION/POPULARITY

#Total ratings by Restaurant
SELECT RESTAURANT,AVG(AVERAGE_RATINGS) AS AVG_RATINGS,SUM(TOTAL_RATINGS) AS TOTAL_SUM FROM SWIGGY 
GROUP BY RESTAURANT ORDER BY AVG_RATINGS DESC,TOTAL_SUM DESC;

#Average Rating of Restaurants in Different Cities
SELECT CITY,ROUND(AVG(AVERAGE_RATINGS),2) AS AVG_RATING FROM SWIGGY GROUP BY CITY ORDER BY AVG_RATING DESC;  #Chennai 3.78  MORE QUALITY

#Average Delivery Time(Mins) of Restaurants in Different Cities
SELECT CITY,ROUND(AVG(DELIVERY_TIME),2) AS AVG_DT FROM SWIGGY GROUP BY CITY ORDER BY AVG_DT DESC;  #Kolkata	67.81

#Average Cost of Restaurants in Different Cities
SELECT CITY,ROUND(AVG(PRICE),2) AS AVG_PRICE FROM SWIGGY GROUP BY CITY ORDER BY AVG_PRICE DESC;  #Mumbai 393.79

#Total Ratings vs. Average Ratings
SELECT Average_Ratings, SUM(Total_Ratings) AS Total_Ratings FROM SWIGGY GROUP BY Average_Ratings ORDER BY Average_Ratings;
#ANOMALY CHECKING
SELECT Restaurant,Total_Ratings FROM SWIGGY WHERE Average_Ratings = 2.9 ORDER BY Total_Ratings DESC;
#Count of restaurants in each city with an average rating of 2.9
SELECT CITY, COUNT(Restaurant) AS Restaurant_Count FROM SWIGGY WHERE Average_Ratings = 2.9 GROUP BY CITY ORDER BY Restaurant_Count DESC;

#Top Restaurants by Average Rating and Price
SELECT Restaurant,Average_Ratings,Price FROM SWIGGY
ORDER BY Average_Ratings DESC, Price ASC LIMIT 10;

#Delivery Time Impact on Ratings
SELECT DELIVERY_TIME,AVG(AVERAGE_RATINGS) AS AVG_RATING FROM SWIGGY GROUP BY DELIVERY_TIME ORDER BY DELIVERY_TIME;

#Count of Restaurants by Rating Category and City
SELECT CITY,RATING_CATEGORY,COUNT(*) AS Restaurant_Count
FROM SWIGGY
GROUP BY CITY, RATING_CATEGORY
ORDER BY CITY, Restaurant_Count DESC;

#How many restaurants are rated as 'Excellent'?
SELECT COUNT(RESTAURANT) AS TOP_RATING FROM SWIGGY WHERE RATING_CATEGORY = 'Excellent';

#What is the average price for different types of food, and which food types are the most expensive?
SELECT FOOD_TYPE, AVG(PRICE) AS AVG_PRICE FROM SWIGGY GROUP BY FOOD_TYPE ORDER BY AVG_PRICE DESC LIMIT 5;

#Which restaurants have the highest ratings and the most total reviews?
SELECT RESTAURANT, AVG(AVERAGE_RATINGS) AS AVG_RATINGS, SUM(TOTAL_RATINGS) AS TOTAL_SUM FROM SWIGGY 
GROUP BY RESTAURANT ORDER BY AVG_RATINGS DESC, TOTAL_SUM DESC LIMIT 5;

SELECT DELIVERY_TIME, AVG(AVERAGE_RATINGS) AS AVG_RATING FROM SWIGGY GROUP BY DELIVERY_TIME ORDER BY DELIVERY_TIME LIMIT 10;

SELECT Address, COUNT(*) AS Frequency FROM SWIGGY 
GROUP BY Address ORDER BY Frequency DESC LIMIT 5;

SELECT FOOD_TYPE, AVG(AVERAGE_RATINGS) AS AVG_RATING, AVG(PRICE) AS AVG_PRICE FROM SWIGGY GROUP BY FOOD_TYPE 
ORDER BY AVG_RATING DESC, AVG_PRICE DESC LIMIT 5;




